bm/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.bm, name='bm'),
]

mar/urls.py
from django.urls import path

from . import views

app_name = "mar"

urlpatterns = [
    path("scheduled", views.scheduled, name="scheduled"),
    path("prn", views.prn, name="prn"),
]

z_django/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from zboard import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", views.login_user, name="login"),
    path("", views.home, name="home"),
    path("meds/", include("meds.urls")),
    path("mar/", include("mar.urls")),
    path("bm/", include("bm.urls")),
    path("equipment/", include("equipment.urls")),
    path("notes/", include("notes.urls")),
    path('seizure/', include('seizure.urls')),
    path('interventions/', include('interventions.urls'))
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

z_django/templates/utils/messages.html
{% if messages %}
{% for message in messages %}
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path
            d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path
            d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
    </symbol>
</svg>

{% if message.tags == 'warning' or message.tags == 'primary' %}
<div class="alert alert-{{ message.tags }} alert-dismissible d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24">
        <use xlink:href="#exclamation-triangle-fill" />
    </svg>
    <div>
        {{message}}
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<!-- SUCCESS MESSAGE! -->
{% else %}
<div class="alert alert-success alert-dismissible d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24">
        <use xlink:href="#check-circle-fill" />
    </svg>
    <div>
        {{message}}
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
{% endfor %} {% endif %}

z_django/templates/utils/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Z-Board</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    {% url 'home' as home_url %}
    {% url 'interventions' as int_url %}
    {% url 'mar:scheduled' as mar_sched_url %}
    {% url 'mar:prn' as mar_prn_url %}
    {% url 'bm' as bm_url %}
    {% url 'seizure' as sz_url %}
    {% url 'equipment' as eq_url%}
    {% url 'notes' as notes_url%}

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item{% if request.path == home_url %} active {% endif%} nav-link" href="{% url 'home' %}">Home</a>
        <li class="nav-item dropdown">
          <a class=" nav-link {% if request.path == mar_prn_url %} active {% elif request.path == mar_sched_url %}active{% endif %} dropdown-toggle "
            href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            MAR
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li>
              <a class="dropdown-item" href="{% url 'mar:scheduled' %}">Scheduled Meds</a>
            </li>
            <li><a class="dropdown-item" href="{% url 'mar:prn'%}">PRN Meds</a></li>
          </ul>
        </li>
        <a class=" nav-item {% if request.path == int_url %}active{% endif %} nav-link"
          href="{% url 'interventions' %}">Interventions</a>

        <a class=" nav-item {% if request.path == sz_url %}active{% endif %} nav-link" href="{% url 'seizure' %}">Seizure
          Log</a>
        <a class=" nav-item {% if request.path == bm_url %}active{% endif %} nav-link" href="{% url 'bm' %}">BM log
        </a>
        <a class=" nav-item {% if request.path == eq_url %}active{% endif %} nav-link"
          href="{% url 'equipment' %}">Equipment</a>

        <a class=" nav-item {% if request.path == notes_url %}active{% endif %} nav-link"
          href="{% url 'notes' %}">Notes</a>
      </div>
    </div>
  </div>
</nav>