bm/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.bm, name='bm'),
]

meds/urls.py
from django.urls import path

from . import views

app_name = "meds"

urlpatterns = [
    # scheduled meds
    path("add/scheduled", views.add_schedule, name="add_sched"),
    path("detail/scheduled/<int:id>", views.detail_schedule, name="detail_sched"),
    path("delete/scheduled/<int:id>", views.delete_schedule, name="delete_sched"),
    # Prn Meds
    path("add/prn", views.add_prn, name="add_prn"),
    path("detail/prn/<int:id>", views.detail_prn, name="detail_prn"),
    path("delete/prn/<int:id>", views.delete_prn, name="delete_prn"),
]

z_django/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from zboard import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", views.login_user, name="login"),
    path("", views.home, name="home"),
    path("meds/", include("meds.urls")),
    path("mar/", include("mar.urls")),
    path("bm/", include("bm.urls")),
    path("equipment/", include("equipment.urls")),
    path("notes/", include("notes.urls")),
    path('seizure/', include('seizure.urls')),
    path('interventions/', include('interventions.urls'))
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

meds/models.py
from django.db import models


# Create your models here.
class ScheduledMed(models.Model):
    name = models.CharField(max_length=200)
    dose = models.CharField(max_length=200)
    frequency = models.CharField(max_length=200)
    times = models.CharField(max_length=200)

    def times_as_list(self):
        return self.times.split(" ")

    def time_count(self):
        return len(self.times.split(" "))

    def __str__(self):
        return self.name


class PrnMed(models.Model):
    name = models.CharField(max_length=200)
    dose = models.CharField(max_length=200)
    indication = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.name} - {self.dose}'

meds/forms.py
from django import forms


class ScheduledMedForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"})
    )
    dose = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"})
    )
    frequency = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"})
    )
    times = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"})
    )


class PrnMedForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"})
    )
    dose = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"})
    )
    indication = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"})
    )

meds/views.py
from django.contrib import messages
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_http_methods

from .forms import PrnMedForm, ScheduledMedForm
from .models import PrnMed, ScheduledMed


# Create your views here.
def add_schedule(request):
    if not request.session.get("logged_in"):
        messages.add_message(request, messages.INFO, "Please log in first")
        return redirect("login")
    if request.method == "POST":
        form = ScheduledMedForm(request.POST)
        if form.is_valid():
            obj = ScheduledMed()
            obj.name = form.cleaned_data["name"]
            obj.dose = form.cleaned_data["dose"]
            obj.frequency = form.cleaned_data["frequency"]
            obj.times = form.cleaned_data["times"]
            obj.save()
            messages.add_message(request, messages.SUCCESS, "Medication added")

            return redirect("home")

    context = {"form": ScheduledMedForm()}
    return render(request, "meds/add_sched.html", context)


def detail_schedule(request, id):
    if not request.session.get("logged_in"):
        messages.add_message(request, messages.INFO, "Please log in first")
        return redirect("login")
    med = ScheduledMed.objects.get(id=id)
    return render(request, "meds/detail_sched.html", {"med": med})


@require_http_methods(["POST"])
def delete_schedule(request, id):
    if not request.session.get("logged_in"):
        messages.add_message(request, messages.INFO, "Please log in first")
        return redirect("login")
    if request.method == "POST":
        med = ScheduledMed.objects.get(id=id)
        med.delete()
        messages.add_message(request, messages.INFO, "Medication deleted")
        return redirect("home")


# PRN Views
def add_prn(request):
    if not request.session.get("logged_in"):
        messages.add_message(request, messages.INFO, "Please log in first")
        return redirect("login")
    if request.method == "POST":
        form = PrnMedForm(request.POST)
        if form.is_valid():
            obj = PrnMed()
            obj.name = form.cleaned_data["name"]
            obj.dose = form.cleaned_data["dose"]
            obj.indication = form.cleaned_data["indication"]
            obj.save()
            messages.add_message(request, messages.SUCCESS, "Medication added")

            return redirect("home")

    context = {"form": PrnMedForm()}
    return render(request, "meds/add_prn.html", context)


def detail_prn(request, id):
    if not request.session.get("logged_in"):
        messages.add_message(request, messages.INFO, "Please log in first")
        return redirect("login")
    med = PrnMed.objects.get(id=id)
    return render(request, "meds/detail_prn.html", {"med": med})


@require_http_methods(["POST"])
def delete_prn(request, id):
    if not request.session.get("logged_in"):
        messages.add_message(request, messages.INFO, "Please log in first")
        return redirect("login")
    if request.method == "POST":
        med = PrnMed.objects.get(id=id)
        med.delete()
        messages.add_message(request, messages.INFO, "Medication deleted")
        return redirect("home")

meds/templates/meds/add_prn.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
zboard | add prn
{% endblock %}

{% block content %}
<div class="container mt-3">

    <!-- Page Title -->
    <div class="row">
        <div class="col-8">
            <p class="lead">Add PRN Medication </p>
        </div>
    </div>



    <form class='card p-3 bg-light' action="" method='POST'>
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="mb-3">
                    <label class="col-sm-4 col-form-label form-control-sm" for="name">{{form.name.label }}</label>
                    <div class="col-sm-8">
                        {{form.name}}
                        {% if form.name.errors %}
                        {% for error in form.name.errors %}
                        <small class="text-danger"> {{error}} </small>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="mb-3">
                    <label class="col-sm-4 col-form-label form-control-sm" for="dose">{{form.dose.label}}</label>
                    <div class="col-sm-8">
                        {{form.dose}}
                        {% if form.dose.errors %}
                        {% for error in form.dose.errors %}
                        <small class="text-danger"> {{error}} </small>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-6">
                <div class="mb-3">
                    <label class="col-sm-4 col-form-label form-control-sm"
                        for="indication">{{form.indication.label}}</label>
                    <div class="col-sm-8">
                        {{form.indication}} {% if form.indication.errors %}
                        <ul class="errors">
                            {% for error in form.indication.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12">
            <input id="submit-button" class="btn btn-primary btn-small" type="submit" value="Enter Medication" />
        </div>


    </form>

</div>
{% endblock %}

meds/templates/meds/add_sched.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
zboard | add schedule
{% endblock %}



{% block content %}
<div class="container mt-3">

    <!-- Page Title -->
    <div class="row">
        <div class="col-8">
            <p class="lead">Add Scheduled Medication </p>
        </div>
    </div>



    <form class='card p-3 bg-light' action="" method='POST'>
        {% csrf_token %}

        <div class="row">
            <div class="col">
                <div class="mb-3">
                    <label class="col-sm-4 col-form-label form-control-sm" for="name">{{form.name.label }}</label>
                    <div class="col-sm-8">
                        {{form.name}}
                        {% if form.name.errors %}
                        {% for error in form.name.errors %}
                        <small class="text-danger"> {{error}} </small>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="mb-3">
                    <label class="col-sm-4 col-form-label form-control-sm" for="dose">{{form.dose.label}}</label>
                    <div class="col-sm-8">
                        {{form.dose}}
                        {% if form.dose.errors %}
                        {% for error in form.dose.errors %}
                        <small class="text-danger"> {{error}} </small>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col">

                <div class="mb-3">
                    <label class="col-sm-4 col-form-label form-control-sm"
                        for="frequency">{{form.frequency.label}}</label>
                    <div class="col-sm-8">
                        {{form.frequency}} {% if form.frequency.errors %}
                        <ul class="errors">
                            {% for error in form.frequency.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="mb-3">
                    <label class="col-sm-4 col-form-label form-control-sm" for="times">{{form.times.label}}</label>
                    <div class="col-sm-8">
                        {{form.times}}
                        {% if form.times.errors %}
                        <ul class="errors">
                            {% for error in form.times.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <input id="submit-button" class="btn btn-primary btn-small" type="submit" value="Enter Medication" />
        </div>
    </form>

</div>
{% endblock %}

meds/templates/meds/detail_prn.html
{% extends 'base.html' %} {% load static %}
<!--start title-->
{% block title %} zboard | {{med.name}} {% endblock %}

{% block styles %}
<style>
  img {
    max-width: 250px;
    max-height: 200px;
  }

</style>
{% endblock %}


<!--Start Body-->
{% block content %}
<div class="container mt-3">
  <div class="card mb-3 w-75">
    <div class="row g-0">
      <div class="col-md-9">
        <div class="card-body">
          <h5 class="card-title">{{med.name}} {{med.dose}}</h5>
          <h6 class="mt-2 card-subtitle mb-2 text-muted">{{med.indication}}</h6>
        </div>
      </div>
      <div class="col">
        <!--img-->
        {% with 'meds/'|add:med.name.lower|add:'.jpeg' as image_static %}
        <img
          src="{% static image_static %}"
          class="img-fluid rounded-start"
          onerror="this.src='{% static 'meds/default.jpeg' %}'"
        />
        {% endwith %}
      </div>
      <div class="card-footer">
        <a
          href="#"
          class="card-link"
          data-bs-toggle="modal"
          data-bs-target="#exampleModal"
          >Delete Med</a
        >

        <a
          target="_blank"
          href="https://www.drugs.com/{{med.name}}.html"
          class="card-link"
          >More info</a
        >
      </div>
    </div>
  </div>

  <div
    class="modal fade"
    id="exampleModal"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">
            Delete {{med.name}}?
          </h5>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this medication?</p>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            Close
          </button>
          <form action="{% url 'meds:delete_prn' med.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}
</div>

meds/templates/meds/detail_sched.html
{% extends 'base.html' %} {% load static %}
<!--start title-->
{% block title %} zboard | {{med.name}} {% endblock %}\

{% block styles %}
<style>
  img {
    max-width: 250px;
    max-height: 200px;
  }

</style>
{% endblock %}

<!--Block body start-->
{% block content %}
<div class="container mt-3">
  <div class="card mb-3 w-75">
    <div class="row g-0">
      <div class="col-md-9">
        <div class="card-body">
          <h5 class="card-title">{{med.name}} {{med.dose}}</h5>

          <div class="mt-3">
            <h6 class="card-subtitle mb-2 text-muted">
              Frequency: {{med.frequency}}
            </h6>
            <h6 class="card-subtitle mb-2 text-muted">Times: {{med.times}}</h6>
          </div>
        </div>
      </div>
      <div class="col">
        <!--img-->
        {% with 'meds/'|add:med.name.lower|add:'.jpeg' as image_static %}

        <img
          src="{% static image_static %}"
          class="img-fluid rounded-start"
          
        />
        {% endwith %}

      </div>
      <div class="card-footer">
        <a
          href="#"
          class="card-link"
          data-bs-toggle="modal"
          data-bs-target="#exampleModal"
          >Delete Med</a
        >

        <a
          target="_blank"
          href="https://www.drugs.com/{{med.name}}.html"
          class="card-link"
          >More info</a
        >
      </div>
    </div>
  </div>

  <div
    class="modal fade"
    id="exampleModal"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">
            Delete {{med.name}}?
          </h5>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this medication?</p>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            Close
          </button>
          <form action="{% url 'meds:delete_sched' med.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}
</div>